export type ServiceCategory = 
  | 'Brows' 
  | 'Lips' 
  | 'Touch-ups' 
  | 'Consultation' 
  | 'Threading' 
  | 'Removal' 
  | 'Treatment' 
  | 'Products' 
  | 'Hair' 
  | 'Makeup';

export interface Service {
  id: string;
  slug: string;
  title: string;
  description: string;
  price: string;
  duration: string;
  whoItsFor: string;
  glossgeniusUrl: string;
  image?: string;
  category: ServiceCategory;
  tags: string[];
  highlights: string[];
  priceValue: number; // Used for sorting.
  durationValue: number; // In minutes, used for sorting.
}

export const services: Service[] = [
  {
    id: "powder-brows",
    slug: "powder-brows",
    title: "Powder Brows",
    description: "Soft, misty shading that mimics the look of filled-in brows with makeup. Perfect for all skin types.",
    price: "$400",
    duration: "3 Hours",
    whoItsFor: "Best for all skin types, including oily/large pores. Perfect if you want a wake-up-and-go makeup look.",
    glossgeniusUrl: "https://eyebrowsbygg.glossgenius.com/services",
    category: "Brows",
    tags: ["Best for Oily Skin", "Defined Look", "Long-lasting"],
    highlights: ["Soft, misty shading", "Defined makeup look", "Long-lasting results"],
    image: "/images/stock/services/brows.jpg",
    priceValue: 400,
    durationValue: 180,
  },
  {
    id: "combo-brows",
    slug: "combo-brows",
    title: "Combo Brows",
    description: "The best of both worlds: natural hair strokes and soft shading for added definition.",
    price: "$450",
    duration: "3 Hours",
    whoItsFor: "Ideal for those wanting natural texture with added density.",
    glossgeniusUrl: "https://eyebrowsbygg.glossgenius.com/services",
    category: "Brows",
    tags: ["Natural & Defined", "Hair Strokes", "Shading"],
    highlights: ["Natural hair strokes", "Soft shading", "Added definition"],
    image: "/images/stock/services/services-hero.jpg",
    priceValue: 450,
    durationValue: 180,
  },
  {
    id: "nanoblading",
    slug: "nanoblading",
    title: "Nanoblading",
    description: "Ultra-realistic hair strokes created with a machine for a natural, fluffy look.",
    price: "$500",
    duration: "3 Hours",
    whoItsFor: "Best for normal to dry skin. Ideal for the most natural 'hair-like' texture.",
    glossgeniusUrl: "https://eyebrowsbygg.glossgenius.com/services",
    category: "Brows",
    tags: ["Best for Dry Skin", "Natural Look", "Fluffy Finish"],
    highlights: ["Hyper-realistic hair strokes", "Natural finish", "Less trauma to skin"],
    image: "/images/stock/services/facial.jpg",
    priceValue: 500,
    durationValue: 180,
  },
  {
    id: "eyebrows-touch-up",
    slug: "eyebrows-touch-up",
    title: "Eyebrows Touch Up",
    description: "Perfecting session for existing clients.",
    price: "$200",
    duration: "1.5 Hours",
    whoItsFor: "Existing clients needing a touch-up.",
    glossgeniusUrl: "https://eyebrowsbygg.glossgenius.com/services",
    category: "Touch-ups",
    tags: ["Maintenance", "Existing Clients"],
    highlights: ["Perfects shape", "Adjusts color"],
    priceValue: 200,
    durationValue: 90,
  },
  {
    id: "yearly-eyebrow-touch-up",
    slug: "yearly-eyebrow-touch-up",
    title: "Yearly Eyebrow Touch Up",
    description: "Annual color refresh.",
    price: "$400",
    duration: "2 Hours",
    whoItsFor: "Existing clients for annual maintenance.",
    glossgeniusUrl: "https://eyebrowsbygg.glossgenius.com/services",
    category: "Touch-ups",
    tags: ["Annual Maintenance", "Color Refresh"],
    highlights: ["Refreshes color", "Keeps brows crisp"],
    image: "/images/stock/portfolio/portfolio-1.jpg",
    priceValue: 400,
    durationValue: 120,
  },
  {
    id: "lip-blush",
    slug: "lip-blush",
    title: "Lip Blush",
    description: "Enhance your natural lip shape and color with a soft wash of pigment.",
    price: "$500",
    duration: "3 Hours",
    whoItsFor: "Anyone wanting defined, tinted lips without daily makeup.",
    glossgeniusUrl: "https://eyebrowsbygg.glossgenius.com/services",
    category: "Lips",
    tags: ["Defined Lips", "Natural Color", "Volume Illusion"],
    highlights: ["Enhances shape", "Soft wash of color", "Natural look"],
    priceValue: 500,
    durationValue: 180,
  },
  {
    id: "lip-blush-touch-up",
    slug: "lip-blush-touch-up",
    title: "Lip Blush Touch Up",
    description: "Perfecting session for lip blush.",
    price: "$250",
    duration: "1.5 Hours",
    whoItsFor: "Existing lip blush clients.",
    glossgeniusUrl: "https://eyebrowsbygg.glossgenius.com/services",
    category: "Touch-ups",
    tags: ["Maintenance", "Lips"],
    highlights: ["Perfects color", "Ensures longevity"],
    priceValue: 250,
    durationValue: 90,
  },
  {
    id: "consultation",
    slug: "consultation",
    title: "Consultation",
    description: "Discuss your goals and eligibility for permanent makeup.",
    price: "$75",
    duration: "30 Mins",
    whoItsFor: "New clients unsure which service is right for them.",
    glossgeniusUrl: "https://eyebrowsbygg.glossgenius.com/services",
    category: "Consultation",
    tags: ["Planning", "Eligibility Check"],
    highlights: ["Personalized advice", "Patch test if needed"],
    priceValue: 75,
    durationValue: 30,
  },
  {
    id: "eyebrow-threading",
    slug: "eyebrow-threading",
    title: "Eyebrow Threading",
    description: "Precision hair removal.",
    price: "$20",
    duration: "15 Mins",
    whoItsFor: "Anyone needing brow shaping.",
    glossgeniusUrl: "https://eyebrowsbygg.glossgenius.com/services",
    category: "Threading",
    tags: ["Shaping", "Precision"],
    highlights: ["Precise shaping", "Quick service"],
    priceValue: 20,
    durationValue: 15,
  },
  {
    id: "eyebrow-threading-and-henna-tinting",
    slug: "eyebrow-threading-and-henna-tinting",
    title: "Eyebrow Threading & Henna Tinting",
    description: "Shape and tint for a bolder look.",
    price: "$45",
    duration: "45 Mins",
    whoItsFor: "Anyone wanting fuller looking brows temporarily.",
    glossgeniusUrl: "https://eyebrowsbygg.glossgenius.com/services",
    category: "Threading",
    tags: ["Tinting", "Shaping", "Bolder Look"],
    highlights: ["Shape & Tint", "Fuller look"],
    priceValue: 45,
    durationValue: 45,
  },
  {
    id: "upper-lip-threading",
    slug: "upper-lip-threading",
    title: "Upper Lip Threading",
    description: "Gentle hair removal.",
    price: "$5",
    duration: "5 Mins",
    whoItsFor: "Anyone needing upper lip hair removal.",
    glossgeniusUrl: "https://eyebrowsbygg.glossgenius.com/services",
    category: "Threading",
    tags: ["Hair Removal"],
    highlights: ["Gentle", "Quick"],
    priceValue: 5,
    durationValue: 5,
  },
  {
    id: "full-face-threading",
    slug: "full-face-threading",
    title: "Full Face Threading",
    description: "Complete facial hair removal.",
    price: "$60",
    duration: "45 Mins",
    whoItsFor: "Anyone needing full face hair removal.",
    glossgeniusUrl: "https://eyebrowsbygg.glossgenius.com/services",
    category: "Threading",
    tags: ["Full Face", "Smooth Skin"],
    highlights: ["Complete removal", "Smooth results"],
    priceValue: 60,
    durationValue: 45,
  },
  {
    id: "natural-tattoo-removal-vitamin",
    slug: "natural-tattoo-removal-vitamin",
    title: "Natural Tattoo Removal + Vitamin",
    description: "Gentle removal of unwanted pigment.",
    price: "$150",
    duration: "1 Hour",
    whoItsFor: "Clients with old or unwanted PMU.",
    glossgeniusUrl: "https://eyebrowsbygg.glossgenius.com/services",
    category: "Removal",
    tags: ["Correction", "Removal"],
    highlights: ["Gentle process", "Vitamin enriched"],
    priceValue: 150,
    durationValue: 60,
  },
  {
    id: "natural-eyebrow-growth",
    slug: "natural-eyebrow-growth",
    title: "Natural Eyebrow Growth",
    description: "Stimulate natural brow growth.",
    price: "$500",
    duration: "1 Hour",
    whoItsFor: "Those looking to restore natural brow hair.",
    glossgeniusUrl: "https://eyebrowsbygg.glossgenius.com/services",
    category: "Treatment",
    tags: ["Growth", "Restoration"],
    highlights: ["Stimulates growth", "Natural restoration"],
    priceValue: 500,
    durationValue: 60,
  },
  {
    id: "eyebrow-growth-serum-3-products",
    slug: "eyebrow-growth-serum-3-products",
    title: "Eyebrow Growth Serum (3 products)",
    description: "Take-home care kit.",
    price: "$175",
    duration: "N/A",
    whoItsFor: "Home care.",
    glossgeniusUrl: "https://eyebrowsbygg.glossgenius.com/services",
    category: "Products",
    tags: ["Home Care", "Products"],
    highlights: ["Take-home kit", "Promotes growth"],
    priceValue: 175,
    durationValue: 0,
  },
  {
    id: "hair-treatment",
    slug: "hair-treatment",
    title: "Hair Treatment",
    description: "Advanced hair restoration treatment.",
    price: "$1000",
    duration: "Consultation",
    whoItsFor: "Hair restoration candidates.",
    glossgeniusUrl: "https://eyebrowsbygg.glossgenius.com/services",
    category: "Hair",
    tags: ["Restoration", "Advanced"],
    highlights: ["Advanced treatment", "Restoration"],
    priceValue: 1000,
    durationValue: 60,
  },
  {
    id: "make-up",
    slug: "make-up",
    title: "Make-up",
    description: "Professional makeup application.",
    price: "$100",
    duration: "1 Hour",
    whoItsFor: "Special occasions.",
    glossgeniusUrl: "https://eyebrowsbygg.glossgenius.com/services",
    category: "Makeup",
    tags: ["Special Occasion", "Professional"],
    highlights: ["Professional application", "Flawless look"],
    priceValue: 100,
    durationValue: 60,
  },
  {
    id: "kids-make-up",
    slug: "kids-make-up",
    title: "Kids Make-up",
    description: "Light makeup for special occasions.",
    price: "$50",
    duration: "30 Mins",
    whoItsFor: "Children for events.",
    glossgeniusUrl: "https://eyebrowsbygg.glossgenius.com/services",
    category: "Makeup",
    tags: ["Kids", "Light Makeup"],
    highlights: ["Age appropriate", "Fun"],
    priceValue: 50,
    durationValue: 30,
  }
];

export function getServiceBySlug(slug: string): Service | undefined {
  return services.find((service) => service.slug === slug);
}
